require('nikanzeyaei.lazy')
require('nikanzeyaei.remaps')
require('nikanzeyaei.sets')
require('nikanzeyaei.harpoon')
require('nikanzeyaei.treesitter')
require('nikanzeyaei.telescope')
require('nikanzeyaei.lsp')
